"""Interactive knowledge-base intake: an agent runs this WITH the human.

Prints the question list (not a form). The agent captures answers
conversationally, then writes draft YAML with every achievement marked
``verified: false``. The human flips flags to true ONLY for claims they
can defend in an interview. Unverified bullets never render.
"""

QUESTIONS = """
Per position:
  1. Employer, title, location, start/end dates — exact.
  2. Team shape: how many people, what did YOU own vs. support?
  3. Which tools did you use, and which were exclusive to THIS employer?
     (employer_scope prevents cross-employer contamination.)
  4. What numbers can you defend if an interviewer probes? ("30% fewer
     incidents" needs a source: dashboard, review doc, manager reference.)
  5. Anything you must NEVER be accused of claiming? (DBA work you only
     supported? A platform your team merely consumed?) → scope_facts +
     forbidden_phrases.

Skills:
  6. For each tool: production / working / limited / homelab?
     production = you operated it in a real job and can whiteboard it.

Final gate:
  7. Read every bullet aloud. Would you say it to that manager's face?
     If not, rewrite or drop it.
"""

DRAFT_TEMPLATE = """# Draft KB generated by intake — EVERY achievement starts verified: false.
# Flip to true only after human review (see docs/kb-guide.md).
# Write these files under $HUNT_DATA/knowledge/, never into the Hunt source tree.

positions:
  - id: {pid}
    title: "{title}"
    employer: "{employer}"
    location: "{location}"
    start: "{start}"
    end: "{end}"
    scope_facts: []
    verified: true
    default_achievements: []

achievements: []

skills:
  skill_groups: []
"""


def print_intake() -> None:
    print(QUESTIONS)
    print("Agent: capture answers conversationally, then emit draft YAML")
    print("modeled on example-workspace/knowledge/. Mark every achievement verified: false.\n")
    print(
        DRAFT_TEMPLATE.format(
            pid="pos1",
            title="...",
            employer="...",
            location="...",
            start="YYYY-MM",
            end="YYYY-MM|present",
        )
    )
